DROP TABLE IF EXISTS Shift CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS Dish CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Cafe CASCADE;
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Job_Title CASCADE;
DROP TABLE IF EXISTS Dish_Order CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;



CREATE TABLE Person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password varchar(20) NOT NULL
);

CREATE TABLE Cafe (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    address varchar(100) NOT NULL,
    user_id int REFERENCES Person(id) ON DELETE CASCADE,
    places int
);

CREATE TABLE Job_Title (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE Shift (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    cafe_id bigint REFERENCES Cafe(id) ON DELETE CASCADE
);

CREATE TABLE Employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(100) NOT NULL,
    phone varchar(100) NOT NULL,
    job_title_id varchar(100) NOT NULL,
    cafe_id bigint REFERENCES Cafe(id) ON DELETE CASCADE,
    shift_id bigint REFERENCES Shift(id) ON DELETE SET NULL
);

CREATE TABLE Dish (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    price money,
    cafe_id bigint REFERENCES Cafe(id) ON DELETE CASCADE
);

CREATE TABLE "Order" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    made_at date,
    comment text,
    status int,
    cafe_id bigint REFERENCES Cafe(id) ON DELETE CASCADE
);

CREATE TABLE Dish_Order (
    order_id bigint REFERENCES "Order"(id) ON DELETE CASCADE,
    dish_id bigint REFERENCES Dish(id) ON DELETE CASCADE
);

CREATE TABLE Reservation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number int,
    peopleAmount int,
    comment text,
    cafe_id bigint REFERENCES Cafe(id) ON DELETE CASCADE
);

INSERT INTO Person(id, username, password) VALUES (0, 'test', 'test');

INSERT INTO Cafe(id, name, address, user_id) VALUES (0, 'Test cafe 1', '1215 Morgan Street', 0);

INSERT INTO Job_Title(id, name) VALUES (0, 'Cook');
INSERT INTO Job_Title(id, name) VALUES (1, 'Waiter');
INSERT INTO Job_Title(id, name) VALUES (2, 'Chef');
INSERT INTO Job_Title(id, name) VALUES (3, 'Sous chef');

INSERT INTO Shift(id, name, cafe_id) VALUES (0, 'From 6.00 to 18.00', 0);
INSERT INTO Shift(id, name, cafe_id) VALUES (1, 'From 8.00 to 20.00', 0);
INSERT INTO Shift(id, name, cafe_id) VALUES (2, 'From 10.00 to 22.00', 0);

